### ISSUE TITLE
Kanban React Project

### ISSUE THREAD

**Issue by MasumaJaffery** [MasumaJaffery/space-travelers-hub#25]
Hello CR!
I hope you are doing great!
- Our Project Kanban Board https://github.com/users/MasumaJaffery/projects/3
- Our Project Name is Space Travelers Hub.
- Our Project Team consists of two coding partners @MasumaJaffery and @najibullahjafari .
- Our Project have two main concerns;
1. Rockets.
2. Missions.
-  @MasumaJaffery Works on Rockets Section (7 Tasks).
- @najibullahjafari Works on Mission Section. (7 Tasks).
- The Other Tasks are Group Tasks.
Thanks for reviewing our Kanban Board!🤓 
Stay Blessed ⭐

**Comment by Davidosky007** [comment]
Hi @MasumaJaffery @najibullahjafari 👋, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights
* All team members' information provided 👍 
* Link to board works 👍 

## Required Changes ♻️
* Kindly add to all the cards as one of the cards is missing points [Check requirements](https://github.com/microverseinc/curriculum-react-redux/blob/main/group-project/setup_kanban_board.md#:~:text=Make%20sure%20that%20each%20card%20starts%20with%20%5BXpt%5D%20%2D%20that%20number%20indicates%20the%20number%20of%20points%20that%20shows%20how%20complex%20the%20task%20is.%201%20point%20%3D%201%20hour%20of%20work.) see screenshot below 👇 
![image](https://github.com/MasumaJaffery/space-travelers-hub/assets/52497246/7339e4c4-a028-4a68-b8ed-07d17c0f270e)

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me @davidsoky007 in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by MasumaJaffery** [comment]
Hello @Davidosky007 I would be grateful if you specify which card requirement is missing?
I analyze it again but I didn't able to find.
Thank You 🙏🏻

**Comment by Davidosky007** [comment]
> Hello @Davidosky007 I would be grateful if you specify which card requirement is missing?
> I analyze it again but I didn't able to find.
> Thank You 🙏🏻

Kindly read my comments you will see you are required to add points to all cards and in the screenshot I highlighted the card with no point

**Comment by OyePriscilla** [comment]
Hi @MasumaJaffery and @najibullahjafari 👏 👏, 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 
![200](https://user-images.githubusercontent.com/103386183/196424328-985f6e98-f7c6-4cf9-bafe-158436f70560.gif)

## Highlights
Added points to all cards :mark

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._
